import torch
import torch.nn as nn
import math
# from .timm import trunc_normal_, Mlp
import einops
import torch.utils.checkpoint

class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

if hasattr(torch.nn.functional, 'scaled_dot_product_attention'):
    ATTENTION_MODE = 'flash'
else:
    try:
        import xformers
        import xformers.ops
        ATTENTION_MODE = 'xformers'
    except:
        ATTENTION_MODE = 'math'

print(f'attention mode is {ATTENTION_MODE}')


def timestep_embedding(timesteps, dim, max_period=10000):
    """
    Create sinusoidal timestep embeddings.

    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional. Can also be a scalar (0-D tensor).
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
    half = dim // 2
    freqs = torch.exp(
        -math.log(max_period) * torch.arange(start=0, end=half, dtype=torch.float32) / half
    ).to(device=timesteps.device)
    
    # 处理标量输入（0维张量）
    if timesteps.dim() == 0:
        # 将标量转换为1维张量 [1]
        timesteps = timesteps.view(1)
    
    args = timesteps[:, None].float() * freqs[None]
    embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
    if dim % 2:
        embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
    return embedding


def patchify(imgs, patch_size):
    x = einops.rearrange(imgs, 'B C (h p1) (w p2) -> B (h w) (p1 p2 C)', p1=patch_size, p2=patch_size)
    return x


def unpatchify(x, channels=3):
    patch_size = int((x.shape[2] // channels) ** 0.5)
    h = w = int(x.shape[1] ** .5)
    assert h * w == x.shape[1] and patch_size ** 2 * channels == x.shape[2]
    x = einops.rearrange(x, 'B (h w) (p1 p2 C) -> B C (h p1) (w p2)', h=h, p1=patch_size, p2=patch_size)
    return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x):
        B, L, C = x.shape

        qkv = self.qkv(x)
        if ATTENTION_MODE == 'flash':
            qkv = einops.rearrange(qkv, 'B L (K H D) -> K B H L D', K=3, H=self.num_heads).float()
            q, k, v = qkv[0], qkv[1], qkv[2]  # B H L D
            x = torch.nn.functional.scaled_dot_product_attention(q, k, v)
            x = einops.rearrange(x, 'B H L D -> B L (H D)')
        elif ATTENTION_MODE == 'xformers':
            qkv = einops.rearrange(qkv, 'B L (K H D) -> K B L H D', K=3, H=self.num_heads)
            q, k, v = qkv[0], qkv[1], qkv[2]  # B L H D
            x = xformers.ops.memory_efficient_attention(q, k, v)
            x = einops.rearrange(x, 'B L H D -> B L (H D)', H=self.num_heads)
        elif ATTENTION_MODE == 'math':
            qkv = einops.rearrange(qkv, 'B L (K H D) -> K B H L D', K=3, H=self.num_heads)
            q, k, v = qkv[0], qkv[1], qkv[2]  # B H L D
            attn = (q @ k.transpose(-2, -1)) * self.scale
            attn = attn.softmax(dim=-1)
            attn = self.attn_drop(attn)
            x = (attn @ v).transpose(1, 2).reshape(B, L, C)
        else:
            raise NotImplemented

        x = self.proj(x)
        x = self.proj_drop(x)
        return x


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None,
                 act_layer=nn.GELU, norm_layer=nn.LayerNorm, skip=False, use_checkpoint=False):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale)
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer)
        self.mlp2 = nn.Sequential(
            nn.Linear(dim, int(dim * mlp_ratio)),
            nn.GELU(),
            nn.Linear(int(dim * mlp_ratio), dim),
        )
        self.skip_linear = nn.Linear(2 * dim, dim) if skip else None
        self.use_checkpoint = use_checkpoint
        # 使用 PyTorch 内置的多头注意力，不依赖自定义 Attention 类
        self.norm3 = norm_layer(dim)
        self.norm4 = norm_layer(dim)
        self.norm5 = norm_layer(dim)
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=dim,
            num_heads=num_heads,
            dropout=0.0,
            batch_first=True
        )

    def forward(self, x, skip=None):
        if self.use_checkpoint:
            return torch.utils.checkpoint.checkpoint(self._forward, x, skip)
        else:
            return self._forward(x, skip)

    def _forward(self, x, skip=None):
        if self.skip_linear is not None:
            # Concat + Linear Proj
            # x = self.skip_linear(torch.cat([x, skip], dim=-1))  # skip conn  in the final dimension
            # Cross attention
            x = self.norm3(x)
            skip = self.norm4(skip)

            x_res = self.cross_attn(x, skip, skip)[0]  # Q K V
            x = x + x_res # 残差链接
            x = x + self.mlp2(self.norm5(x))
            # print(f"拥有跳跃链接时输出的 x 的形状为:{x.shape}")  # [8, 257, 768]

        # transformer block
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x


class PatchEmbed(nn.Module):
    """ Image to Patch Embedding
    """
    def __init__(self, patch_size, in_chans=3, embed_dim=768):
        super().__init__()
        self.patch_size = patch_size
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)

    def forward(self, x):
        B, C, H, W = x.shape
        assert H % self.patch_size == 0 and W % self.patch_size == 0
        x = self.proj(x).flatten(2).transpose(1, 2)
        return x


class UViT(nn.Module):
    def __init__(self, img_size=256, patch_size=16, in_chans=6, embed_dim=768, depth=12, num_heads=12, mlp_ratio=4.,
                 qkv_bias=False, qk_scale=None, norm_layer=nn.LayerNorm, mlp_time_embed=False,
                 use_checkpoint=False, conv=True, skip=True, has_image = True):
        super().__init__()
        self.num_features = self.embed_dim = embed_dim  # num_features for consistency with other models
        self.in_chans = in_chans

        self.patch_embed = PatchEmbed(patch_size=patch_size, in_chans=in_chans, embed_dim=embed_dim)
        self.patch_embed2 = PatchEmbed(patch_size=patch_size, in_chans=in_chans, embed_dim=embed_dim)
        
        num_patches = (img_size // patch_size) ** 2   # 算上通道数

        self.time_embed = nn.Sequential(
            nn.Linear(embed_dim, 4 * embed_dim),
            nn.SiLU(),
            nn.Linear(4 * embed_dim, embed_dim),
        ) if mlp_time_embed else nn.Identity()

        if has_image:
            self.image_embed = nn.Linear(1024 * 2, embed_dim)
        
        if has_image:
            # self.extras = 257
            self.extras = 1
        else:
            self.extras = 1

        self.pos_embed = nn.Parameter(torch.zeros(1, self.extras + num_patches, embed_dim))
        self.pos_embed2 = nn.Parameter(torch.zeros(1, num_patches, embed_dim))  # 这里不添加额外维度：time 
        
        
        self.in_blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                norm_layer=norm_layer, use_checkpoint=use_checkpoint)
            for _ in range(depth // 2)])
        # 模拟出真实图像的特征
        self.cond_in_blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                norm_layer=norm_layer, use_checkpoint=use_checkpoint)
            for _ in range(depth // 2)])

        self.mid_block = Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                norm_layer=norm_layer, use_checkpoint=use_checkpoint)

        self.out_blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                norm_layer=norm_layer, skip=skip, use_checkpoint=use_checkpoint)
            for _ in range(depth // 2)])

        self.norm = norm_layer(embed_dim)
        self.patch_dim = patch_size ** 2 * in_chans
        self.decoder_pred = nn.Linear(embed_dim, self.patch_dim, bias=True)
        self.final_layer = nn.Conv2d(self.in_chans, self.in_chans, 3, padding=1) if conv else nn.Identity()
       
        # self.coarse_diff_linear = nn.Sequential(
        #     nn.Linear(embed_dim, 4 * embed_dim),
        #     nn.SiLU(),
        #     nn.Dropout(0.1),
        #     nn.Linear(4 * embed_dim, embed_dim),
        # ) 

        self.fine_conv = nn.Conv2d(self.in_chans, self.in_chans, 3, 1, 1)
        self.coarse_init_conv = nn.Conv2d(self.in_chans * 2, self.in_chans, 3, 1, 1) # coarse init conv
        self.init_conv  = nn.Conv2d(self.in_chans * 2, self.in_chans, 1) # 1 * 1 卷积


        trunc_normal_(self.pos_embed, std=.02)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    @torch.jit.ignore
    def no_weight_decay(self):
        return {'pos_embed'}

    def forward(self, x, timesteps, condition):  # y = (coarse_image_1, coarse_image_2, fine_image_1)
        _device = x.device
        x = self.patch_embed(x)  # 展开 x
        B, L, D = x.shape

        time_token = self.time_embed(timestep_embedding(timesteps, self.embed_dim))
        time_token = time_token.unsqueeze(dim=1).to(_device)
        # 条件分支
        if True:
            # print(f"拥有条件分支")
            # assert x.shape[1] == 256, f"x.shape[1] is {x.shape[1]}, but should be 256"
            c1, c2, f1 = condition.split(6, dim=1)
            x_fine = self.fine_conv(f1)
            x_coarse = self.coarse_init_conv(
                torch.cat((c1, c2), dim=1)
            )
            
            x_clean = torch.cat((x_fine, x_coarse), dim=1)  # 2C
            x_clean = self.init_conv(x_clean)     # C
            # print(f"x clean 的形状是:{x_clean.shape}")   # [8, 6, 256, 256]
            x_clean = self.patch_embed2(x_clean)
            # print(f"展开后 x clean 的形状是:{x_clean.shape}")   # [8, 256, 768]
            x_clean = x_clean + self.pos_embed2
            # print(f"添加位置编码后 x clean 的形状是:{x_clean.shape}")   # [8, 256, 768]

        # x = x_noise
        x = torch.cat((time_token, x), dim=1)  # timestep
        x = x + self.pos_embed
        # print(f"x的形状是 {x.shape}") # [8, 257, 768]

        """
            每次两个stream的输出相减 结果跳跃连接至Decoder
        """

        "noise 分支"
        noise_skips = []
        for blk in self.in_blocks:
            x = blk(x)
            noise_skips.append(x)
        # print(f"noise 之后 x的形状是 {x.shape}")  # [8, 257, 768]

        "clean 分支"
        clean_skips = []
        for blk in self.cond_in_blocks:
            x_clean = blk(x_clean)
            clean_skips.append(x_clean)

        "计算残差特征 -- 噪声特征"
        """
            clean is 256
            noise is 257
        """
        skips = []
        for n_skip, c_skip in zip(noise_skips, clean_skips):
            skips.append(n_skip[:, self.extras:, :] - c_skip)  #TODO 这里的中间维度不一样该怎么理解qkv的计算过程呢?
        
        "这里双分支该怎么交互呢?"
        x = self.mid_block(x)

        "注入使用了 交叉注意力; 还需不需要归一化等操作?"
        for blk in self.out_blocks:
            x = blk(x, skips.pop())  # 从末尾开始 pop

        x = self.norm(x)
        x = self.decoder_pred(x)   # 到PathEmbed dim
        assert x.size(1) == self.extras + L    # 中间的维度值
        x = x[:, self.extras:, :]  # 去掉令牌值
        x = unpatchify(x, self.in_chans)
        x = self.final_layer(x)  # 最后一个卷积
        return x
    
    "测试函数"
    def sample(self,c1 ,c2, f1):
        # 从噪声开始
        noisy_img = torch.randn((1, 6, 256, 256)).to("cuda")
        for i, t in enumerate(tqdm.tqdm(scheduler.timesteps)):
            # 1. predict noise residual
            with torch.no_grad():
                residual = model(noisy_img, t, 1, c1, c2, f1).sample
            # 2. compute less noisy image and set x_t -> x_t-1
            noisy_img = self.diffScheduler.step(residual, t, noisy_img).prev_sample
        
        return noisy_img

if __name__ == '__main__':
    device = "cuda"
    c1 = torch.randn(1, 6, 256, 256)
    c2 = torch.randn(1, 6, 256, 256)
    f1 = torch.randn(1, 6, 256, 256)
    f2 = torch.randn(1, 6, 256, 256)
    x = torch.randn(1, 6, 256, 256)
    timesteps = torch.randint(0, 1000, (1,))
    model = UViT(img_size=256, patch_size=16, in_chans=6, embed_dim=768, depth=12, num_heads=12, mlp_ratio=4.,
                 qkv_bias=False, qk_scale=None, norm_layer=nn.LayerNorm, mlp_time_embed=False,
                 use_checkpoint=False, conv=True, skip=True, has_image=True)
    model.to(device)
    # timesteps = timesteps.to(device)
    # x = x.to(device)
    # c1 = c1.to(device)
    # c2 = c2.to(device)
    # f1 = f1.to(device)
    
    # condition = [c1, c2, f1]

    # output = model(x, timesteps, condition)
    # print(output.shape)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters())}") # 281919600
    pass